base_url = "https://simonxiang.xyz"
title = "Home | Simon Xiang"
description = "Simon Xiang's personal website."
compile_sass = false
minify_html = true
generate_feeds = true
default_language = "en"

taxonomies = [
    {name = "tags", feed = true},
]

# todo: change this to JP or CN
[languages.fr]
generate_feeds = true
build_search_index = true

[markdown]
render_emoji = true
external_links_target_blank = true
smart_punctuation = true
highlight_code = false
highlight_theme = "nord"

[slugify]
paths = "on"
taxonomies = "on"
anchors = "on"

[link_checker]
internal_level = "warn"

[extra]
author = "Simon Xiang"
display_author = true

favicon = "favicon.ico"
image = ""

# comment out => respect user theme
# default_theme = "light"
list_pages = false
twitter_card = false

header_nav = [
  { url = "/", name_en = "Home", name_fr = "/accueil/" },
  { url = "/about", name_en = "About", name_fr = "/concernant/" },
  { url = "/resume", name_en = "CV", name_fr = "/concernant/" },
  { url = "/blog", name_en = "Blog", name_fr = "/blog/" }
]
